const mongoose = require('mongoose');

/**
 * CriterionResult sub-schema.
 * Detailed evaluation outcome for a single rubric criterion.
 */
const criterionResultSchema = new mongoose.Schema({
  criterionId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Problem.rubricCriteria'
  },
  criterionName: {
    type: String,
    required: true
  },
  weight: {
    type: Number,
    required: true,
    min: 0,
    max: 1
  },
  score: {
    type: Number,
    required: true,
    min: 0,
    max: 100
  },
  evidence: {
    type: String,
    default: ''
  },
  concern: {
    type: String,
    default: ''
  },
  suggestion: {
    type: String,
    default: ''
  },
  confidence: {
    type: String,
    enum: ['high', 'medium', 'low'],
    default: 'high'
  }
}, { _id: false });

/**
 * EvaluationResult model.
 * Stores the full evaluation report generated by an evaluator.
 * Preserved across retries so learners can see their progression.
 */
const evaluationResultSchema = new mongoose.Schema({
  submissionId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Submission',
    required: true,
    index: true
  },
  attemptId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Attempt',
    required: true,
    index: true
  },
  evaluatorType: {
    type: String,
    enum: ['deterministic', 'mock-ai', 'rule-based'],
    required: true
  },
  criterionResults: [criterionResultSchema],
  overallScore: {
    type: Number,
    required: true,
    min: 0,
    max: 100
  },
  strengths: [{
    type: String
  }],
  concerns: [{
    type: String
  }],
  suggestions: [{
    type: String
  }],
  evaluatedAt: {
    type: Date,
    default: Date.now
  }
}, {
  timestamps: true
});

module.exports = mongoose.model('EvaluationResult', evaluationResultSchema);
